void f3Button(){
    fill(0);
  textSize(50);
  //1列目
  text("教員室", defaultButtonX, defaultButtonY-40);
  f3Button.setFont(font);
  f3Button.addButton("F30311")
    .setLabel("321")
    .setPosition(defaultButtonX, defaultButtonY+(destinationButtonH + betweenH)*0)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F30511")
    .setLabel("322,323,324")
    .setPosition(defaultButtonX, defaultButtonY+(destinationButtonH + betweenH)*1)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);

  f3Button.addButton("F30711")
    .setLabel("325,326,327")
    .setPosition(defaultButtonX, defaultButtonY+(destinationButtonH + betweenH)*2)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F30911")
    .setLabel("328,329,330")
    .setPosition(defaultButtonX, defaultButtonY+(destinationButtonH + betweenH)*3)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F51311")
    .setLabel("321,322,333")
    .setPosition(defaultButtonX, defaultButtonY+(destinationButtonH + betweenH)*4)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  //2列目
  text("教室(mac室)", defaultButtonX+(destinationButtonW + betweenW)*1, defaultButtonY-40);
  f3Button.addButton("F30509")
    .setLabel("363")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*1, defaultButtonY+(destinationButtonH + betweenH)*0)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F50709")
    .setLabel("364")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*1, defaultButtonY+(destinationButtonH + betweenH)*1)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F50909")
    .setLabel("365")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*1, defaultButtonY+(destinationButtonH + betweenH)*2)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F31309")
    .setLabel("大講義室")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*1, defaultButtonY+(destinationButtonH + betweenH)*3)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  //3列目
  text("サークル室", defaultButtonX+(destinationButtonW + betweenW)*2, defaultButtonY-40);
  f3Button.addButton("F51103")
    .setLabel("01,02,03")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*2, defaultButtonY+(destinationButtonH + betweenH)*0)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F51101")
    .setLabel("4,5,6,7")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*2, defaultButtonY+(destinationButtonH + betweenH)*1)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F51301")
    .setLabel("8,9,10,11")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*2, defaultButtonY+(destinationButtonH + betweenH)*2)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F51501")
    .setLabel("12,13,14,15")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*2, defaultButtonY+(destinationButtonH + betweenH)*3)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
    //4列
      text("その他", defaultButtonX+(destinationButtonW + betweenW)*3, defaultButtonY-40);
  f3Button.addButton("F50111")
    .setLabel("C.Cafe3")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*3, defaultButtonY+(destinationButtonH + betweenH)*0)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F50115")
    .setLabel("講堂")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*3, defaultButtonY+(destinationButtonH + betweenH)*1)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
  f3Button.addButton("F50105")
    .setLabel("共同研究室")
    .setPosition(defaultButtonX+(destinationButtonW + betweenW)*3, defaultButtonY+(destinationButtonH + betweenH)*2)
    .setSize(destinationButtonW, destinationButtonH)
    .setColorCaptionLabel(labelColor)
    .setColorBackground(buttonColor)
    .setColorForeground(buttonForegroundColor)
    .setColorLabel(#ffffff)
    .setColorActive(buttonActiveColor);
}
